version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - ./db_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"

  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always    
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      # MYSQL_PASSWORD: example 
      # MYSQL_USER: example

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:9010"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      APACHE_PORT: "9010"
      
  task_server:
    image: task_server:latest
    container_name: task_server
    build: .\serverLogowanie\serverTodoFlusk
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: db

  login_server:
    image: login_server:latest
    container_name: login_server
    build: .\serverLogowanie\loginToServerFlask
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: users


  task_client:
    image: task_client:latest
    container_name: task_client
    build: .\serverLogowanie\todoApp
    depends_on:
      - task_server
    ports:
      - "9000:80"
    volumes:
    - ./vuejs:/project
    - /project/node_modules
  